### PR TITLE
Guacloginpagelinks

### PR DESCRIPTION
**Pull request by ewierschke**
Added sed command just before tomcat service is restarted to modify the JS/HTML within the Guac login page to include DICELAB resource URLs.

### CODE REVIEW

**Comment by lorengordon** [comment]
I'd like to find some way to parameterize the links and strings rather than hard-code them into the script...

**Comment by ewierschke** [comment]
Added parameters for inserting two urls with partner url text to modify guac login page

**Comment by lorengordon** [comment]
Nice! And now to add support to the cfn templates for passing in those parameters... :grinning:

**Comment by lorengordon** [comment]
Build got stuck, closing and re-opening to give it a kick...

**Pull request merged**
